on:
  push:
    branches:
      - master

name: Package and deploy backend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - uses: actions/checkout@master

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_4425c49b }}

    # deploy web app using publish profile credentials
    - uses: azure/webapps-deploy@v1
      with:
        app-name: vginventory-db-api
        package: src/infra/webapi

    # Azure logout
    - name: logout
      run: |
        az logout
